repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustmt
        description: Format files with cargo fmt.
        entry: cargo fmt --manifest-path=back/Cargo.toml
        pass_filenames: false
        language: system

      - id: prettier
        name: prettier
        description: Format files with prettier
        entry: prettier -w front
        pass_filenames: false
        language: system
