services:
  server:
    build:
      args:
        - VITE_BAR_NAME=${VITE_BAR_NAME}
        - DATABASE_FILE=biere-n-collect.db
        - DATABASE_URL=sqlite:biere-n-collect.db
      context: .
    volumes:
      - ./.env:/app/.env
      - ./back/biere-n-collect.db:/app/biere-n-collect.db
    image: ${DOCKER_IMAGE_URL_BASE}biere-n-collect:latest
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite:biere-n-collect.db

volumes:
  sqlite-data:
