services:
  test-back:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - DATABASE_FILE=biere-n-collect.db
        - DATABASE_URL=sqlite:biere-n-collect.db
    environment:
      - DATABASE_URL=sqlite:biere-n-collect.db
