services:
  db:
    image: mariadb:10.6.16
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: lhavrais-pay
    volumes:
      - sql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      retries: 10
      interval: 5s
    networks:
      - helibot
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - .env:/.env
  #     - ./helibot.toml:/helibot.toml
  #   image: ${DOCKER_IMAGE_URL_BASE}helibot:latest
  #   environment:
  #     - MARIADB_HOST=db
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - helibot

volumes:
  sql-data:

networks:
  helibot: