services:
  db:
    image: mariadb:10.6.16
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: lhavrais-pay
    volumes:
      - sql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      retries: 10
      interval: 5s
    networks:
      - lhavrais-pay
  server:
    build:
      context: .
      args:
        - VITE_SITE_URL=${VITE_SITE_URL}
        - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ${PWD}/.env:/app/.env
    image: ${DOCKER_IMAGE_URL_BASE}lhavrais-pay:latest
    ports:
      - 8000:8000
    environment:
      - MARIADB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lhavrais-pay

volumes:
  sql-data:

networks:
  lhavrais-pay:
