FROM rust:1-bookworm


RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/biere-n-collect/target \
    cargo install sqlx-cli

ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

WORKDIR /app/biere-n-collect/

COPY back/Cargo.toml Cargo.toml
COPY back/src/ src/

#/!\ please make sure to run `cargo sqlx prepare` before
COPY back/.sqlx .sqlx
COPY back/migrations migrations


# RUN --mount=type=cache,target=/usr/local/cargo/registry \
#     --mount=type=cache,target=/app/biere-n-collect/target \
#     sqlx migrate run

# RUN --mount=type=cache,target=/usr/local/cargo/registry \
#     --mount=type=cache,target=/app/biere-n-collect/target \
#     cargo sqlx prepare -- --tests

# RUN --mount=type=cache,target=/usr/local/cargo/registry \
#     --mount=type=cache,target=/app/biere-n-collect/target \
#     cargo build --tests

ENV SQLX_OFFLINE ""

CMD ["sh", "-c", "sqlx migrate run && cargo test"]
