FROM rust:1-bookworm

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG DATABASE_FILE

WORKDIR /app/biere-n-collect/

COPY back/Cargo.toml Cargo.toml
COPY back/src/ src/

COPY back/migrations migrations
COPY back/$DATABASE_FILE $DATABASE_FILE

RUN cargo build --tests

CMD ["cargo", "test"]
