FROM rust:1-bookworm

ENV SQLX_OFFLINE true

WORKDIR /app/biere-n-collect/

COPY back/Cargo.toml Cargo.toml
COPY back/src/ src/

#/!\ please make sure to run `cargo sqlx prepare -- --tests` before
COPY back/.sqlx .sqlx
COPY back/migrations migrations


RUN cargo build --tests

CMD ["cargo", "test"]
