CREATE TABLE IF NOT EXISTS Orders
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RECEIPT VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ProductTypes
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Stocks
(
    product_id INT UNSIGNED,
    stock INT UNSIGNED NOT NULL,
    CONSTRAINT `fk_product_id`
        FOREIGN KEY (product_id) REFERENCES ProductTypes (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);