services:
  test-back:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.e2e
      args:
        - DATABASE_FILE=biere-n-collect.db
        - DATABASE_URL=sqlite:biere-n-collect.db
    volumes:
      - ../.env:/app/.env
      - ../back/biere-n-collect.db:/app/biere-n-collect.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      timeout: 30s
      interval: 1m
      start_interval: 1s
      start_period: 30s
      retries: 3
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite:biere-n-collect.db
      - SMTP_USERNAME=infos@bnc
      - SMTP_PASSWORD=azerty # server panics if not present
      - SMTP_HOST=mailer
      - SMTP_PORT=25
      - STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
    networks:
      - e2e
  mailer:
    image: rnwood/smtp4dev
    ports:
      - 5000:80  # web interface
      - 25:25  # web interface
    environment:
      - ServerOptions__TlsMode=StartTls
      - Serveroptions__HostName=mailer
    networks:
      - e2e
  e2e:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.cypress
    volumes:
      - ./screenshots:/app/cypress/screenshots
      - ./videos:/app/cypress/videos
    environment:
      - CYPRESS_SERVER_URL=http://test-back:8000
      - CYPRESS_MAIL_API_URL=http://mailer:80
      # - DEBUG=cypress:*
    depends_on:
      mailer:
        condition: service_started
      test-back:
        condition: service_healthy
    networks:
      - e2e
networks:
  e2e:
