# This is a basic workflow to help you get started with Actions

name: build docker image frontend

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: eli-sauvage
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: front
          push: true
          tags: ghcr.io/eli-sauvage/lhavrais-pay-front:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
